duui:
  endpoint: http://localhost:9000
  timeout: 5000

input:
  modalities:
    - text
#    - audio
#    - image
  text-anon-types:
    - blackout
    - replace
  image-anon-types:
    - blur
    - pixel
    - blackout
    - diffused
  audio-anon-types:

cas:
  pool-size: 20
  resource-specifier:
  typesystem-path: 