duui:
  endpoint: http://localhost:9000
  timeout: 5000
  components:
    - REMOTE
    - DOCKER
  text-anon-types:
    - placeholder
    - remove
    #    - pseudo
  text-anon-propeties:
    - model
    - trust_remote_code
    - device
    - placeholder
    - selection_begin
    - selection_end
  image-anon-types:
    - blur
    - pixel
    - blackout
    - diffused
  image-anon-properties:

  audio-anon-types:
  audio-anon-properties:


input:
  modalities:
    - TEXT
#    - AUDIO
#    - IMAGE



cas:
  pool-size: 20
  resource-specifier:
  typesystem-path: 